# Hospital Operations & Patient Risk Intelligence

1. **Business question** - Why are we doing this?
2. **Data logic** - Which tables/columns are involved?
3. **Python logic** - What is each code block doing?
4. **Insight** - What did we observe?
5. **Recommendation** - What should hospital management do?

# 1. Import Libraries and Set File Paths

I first import the tools required for the project.

- `pandas` is used for data cleaning, joining, grouping, and analysis.
- `numpy` is used for numeric operations and missing value handling.
- `sqlite3` is used to connect python with the SQL database.
- `matplotlib` is used for charts.
- `Path` helps us manage folder paths safely.

In [1]:
pip install SQLALchemy pandas pymysql

Requirement already satisfied: SQLALchemy in c:\users\py550\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: pandas in c:\users\py550\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: pymysql in c:\users\py550\anaconda3\lib\site-packages (1.1.2)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\py550\anaconda3\lib\site-packages (from SQLALchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\py550\anaconda3\lib\site-packages (from SQLALchemy) (4.12.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\py550\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\py550\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\py550\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\py550\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\py550\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
pip install sqlalchemy

Requirement already satisfied: sqlalchemy in c:\users\py550\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\py550\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\py550\anaconda3\lib\site-packages (from sqlalchemy) (4.12.2)
Note: you may need to restart the kernel to use updated packages.

In [4]:
from sqlalchemy import create_engine
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

engine = create_engine("mysql+pymysql://root:2310@localhost/hospital_project")

In [5]:
import os
os.listdir(r"C:/Users/py550/Downloads/Hospital_project/")

['admissions_raw.csv',
 'billing_claims_raw.csv',
 'departments.csv',
 'doctors.csv',
 'followups_raw.csv',
 'hospitals.csv',
 'lab_results_raw.csv',
 'patients_raw.csv',
 'pharmacy_orders_raw.csv',
 'treatments_raw.csv']

In [9]:
from sqlalchemy import create_engine
import pandas as pd
import os
import mysql.connector

engine = create_engine("mysql+pymysql://root:2310@localhost/hospital_project")

# Path to the dataset files

Data_Path = (r"C:/Users/py550/Downloads/Hospital_project/")

# MySQL connector config
config = {
    'user': 'root',
    'password': '2310',
    'host': 'localhost',
    'database': 'hospital_project',
    'raise_on_warnings': True
}

# Connect and Insert
try:
    conn = mysql.connector.connect(**config)
    cursor = conn.cursor()
    print("MySQL connection established successfully.")

    csv_files = [
          'admissions_raw.csv',
          'billing_claims_raw.csv',
          'departments.csv',
          'doctors.csv',
          'followups_raw.csv',
          'hospitals.csv',
          'lab_results_raw.csv',
          'patients_raw.csv',
          'pharmacy_orders_raw.csv',
          'treatments_raw.csv'
        ]
    for file in csv_files:
        df = pd.read_csv(os.path.join(Data_Path, file))
        table_name = file.replace('.csv', '').replace('_raw', '')
        df.to_sql(name = table_name, con = engine, if_exists = 'replace', index =False)
        print(f" Table '{table_name}' created successfully.")

except mysql.connector.Error as err:
    print(f" Error: {err}")
finally:
    if conn.is_connected():
        cursor.close()
        conn.close()
        print(" MySQL Connection Closed.")

MySQL connection established successfully.
 Table 'admissions' created successfully.
 Table 'billing_claims' created successfully.
 Table 'departments' created successfully.
 Table 'doctors' created successfully.
 Table 'followups' created successfully.
 Table 'hospitals' created successfully.
 Table 'lab_results' created successfully.
 Table 'patients' created successfully.
 Table 'pharmacy_orders' created successfully.
 Table 'treatments' created successfully.
 MySQL Connection Closed.

# 2. Connect to SQL Database and See Available Tables

In real companies, data usually comes from databases, not direct CSV files.
Here we connect to a SQLite database and check what tables are availables.

This helps understand the database before analysis.

# Read Tables One by One

Instead of using one complex dictionary comprehension, we read important tables one by one.This is longer, but much easier to explain.

In [16]:
patients = pd.read_sql('SELECT * FROM patients;', engine)
admissions = pd.read_sql('SELECT * FROM admissions;', engine)
treatments = pd.read_sql('SELECT * FROM treatments;', engine)
billing = pd.read_sql('SELECT * FROM billing_claims;', engine)
pharmacy = pd.read_sql('SELECT * FROM pharmacy_orders;', engine)
labs = pd.read_sql('SELECT * FROM lab_results;', engine)
followups = pd.read_sql('SELECT * FROM followups;', engine)
doctors = pd.read_sql('SELECT * FROM doctors;', engine)
departments = pd.read_sql('SELECT * FROM departments;', engine)
hospitals = pd.read_sql('SELECT * FROM hospitals;', engine)



print('patients:', patients.shape)
print('admissions:', admissions.shape)
print('treatments:', treatments.shape)
print('billing:', billing.shape)
print('pharmacy:', pharmacy.shape)
print('labs:', labs.shape)
print('followups:', followups.shape)
print('doctors:', doctors.shape)
print('departments:', departments.shape)
print('hospitals:', hospitals.shape)

patients: (12090, 10)
admissions: (30130, 12)
treatments: (90160, 7)
billing: (30080, 10)
pharmacy: (70090, 8)
labs: (60000, 7)
followups: (30000, 7)
doctors: (260, 7)
departments: (12, 3)
hospitals: (8, 6)

# 4. First-Level Data Understanding

Before cleaning, we need to inspect:
- Number of rowss and columns
- column names
- sample records
- Data types
- Missing values

This is like a doctor checking symptoms before treatment.

In [14]:
patients.head()

,patient_id,patient_code,patient_name,age,gender,city,primary_chronic_condition,insurance_plan,income_segment,registration_date
0,1,P00001,Patient_BKOKF,46.0,Female,Hyderabad,Heart Failure,Premium Insurance,Low,2016-09-25
1,2,P00002,Patient_KXPSW,58.0,Male,Hyderabad,Heart Failure,Basic Insurance,Low,2022-09-12
2,3,P00003,Patient_TJAJT,51.0,Female,Ahmedabad,Hypertension,Government Scheme,Middle,2014-08-02
3,4,P00004,Patient_WYKTO,25.0,Male,None,Heart Failure,Self Pay,Middle,2017-03-23
4,5,P00005,Patient_PFFLA,54.0,Male,None,Asthma,Basic Insurance,Middle,2021-11-22

In [17]:
admissions.head()

,admission_id,patient_id,hospital_id,department_id,primary_doctor_id,admission_date,discharge_date,admission_type,diagnosis,severity_level,discharge_status,readmitted_30_days
0,1,3415,8,4,123,2024-03-10,2024-03-16,Emergency,Anemia,Critical,Home,Yes
1,2,3610,8,1,209,2023-05-19,2023-05-20,Planned,Arrhythmia,Moderate,Home,No
2,3,7584,8,3,190,2025-06-16,2025-06-18,Emergency,Joint Replacement,Moderate,Home,Yes
3,4,4459,2,3,176,2025-10-15,2025-10-16,Referral,Joint Replacement,Moderate,Home,No
4,5,5508,3,12,140,2024-05-07,2024-05-23,Planned,Multi Organ Dysfunction,Moderate,Home,No

In [18]:
treatments.head()

,treatment_id,admission_id,doctor_id,treatment_type,treatment_cost,treatment_date,treatment_status
0,1,27337,62,Surgery,52636.30,2023-01-01,Completed
1,2,982,242,Imaging,7478.12,2023-01-01,Completed
2,3,17082,238,Chemotherapy,27451.58,2023-01-01,Completed
3,4,4096,1,Lab Package,3379.43,2023-01-01,Pending
4,5,26108,227,ICU Care,19993.51,2023-01-01,Completed

In [19]:
billing.head()

,bill_id,admission_id,patient_id,payer_type,gross_amount,discount_amount,insurance_paid,patient_paid,claim_status,bill_date
0,1,1,3415,Premium Insurance,19940.46,1785.84,15939.06,2215.56,Paid,2024-03-10
1,2,2,3610,Basic Insurance,19034.64,558.14,13981.49,4495.01,Partial,2023-05-19
2,3,3,7584,Self Pay,20965.03,2413.86,18595.28,0.00,Rejected,2025-06-16
3,4,4,4459,Corporate Insurance,16637.20,1938.84,13657.64,1040.72,Rejected,2025-10-15
4,5,5,5508,Government Scheme,77727.52,2213.24,35959.21,39555.07,Paid,2024-05-07

In [20]:
pharmacy.head()

,order_id,admission_id,patient_id,medicine_name,quantity,unit_price,line_amount,pharmacy_type
0,1,29377,7899,Insulin,15,57.66,864.90,IP Pharmacy
1,2,25956,2404,Anticoagulant,1,33.52,33.52,IP Pharmacy
2,3,18883,6450,Chemotherapy Drug,17,188.65,3207.07,OP Pharmacy
3,4,21967,10792,Metformin,3,37.73,113.18,OP Pharmacy
4,5,17705,4645,Amlodipine,20,95.68,1913.64,OP Pharmacy

In [21]:
labs.head()

,lab_id,admission_id,patient_id,test_name,test_value,test_date,result_flag
0,1,2133,11981,CRP,5.99,2023-01-01,Abnormal
1,2,5569,5064,Sodium,2.46,2023-01-01,Normal
2,3,17271,1824,CRP,2.84,2023-01-01,Abnormal
3,4,24486,9939,HbA1c,14.91,2023-01-01,Normal
4,5,21094,8920,Hemoglobin,11.46,2023-01-01,Abnormal

In [22]:
followups.head()

,followup_id,admission_id,patient_id,followup_due_date,followup_completed,followup_mode,followup_outcome
0,1,1,3415,2024-03-30,Yes,OPD Visit,Stable
1,2,2,3610,2023-05-27,Yes,OPD Visit,Stable
2,3,3,7584,2025-07-02,Yes,Telemedicine,Stable
3,4,4,4459,2025-10-23,No,Call,Referred Back
4,5,5,5508,2024-05-30,Yes,Call,Stable

In [23]:
doctors.head()

,doctor_id,doctor_name,department_id,specialization,hospital_id,experience_years,doctor_grade
0,1,Dr. Sai Sharma,4,General Medicine,8,9,Consultant
1,2,Dr. Raj Nair,12,ICU,7,10,Resident
2,3,Dr. Ishaan Khan,9,Emergency,6,16,Consultant
3,4,Dr. Sai Rao,7,Gastroenterology,7,7,Consultant
4,5,Dr. Priya Menon,2,Neurology,2,12,Senior Consultant

In [24]:
departments.head()

   department_id   department_name care_complexity
0              1        Cardiology            High
1              2         Neurology            High
2              3       Orthopedics          Medium
3              4  General Medicine          Medium
4              5       Pulmonology            High

In [25]:
hospitals.head()

,hospital_id,hospital_name,city,ownership_type,bed_capacity,launch_year
0,1,MedNova Hospital - Hyderabad,Hyderabad,Private,420,2009
1,2,MedNova Hospital - Bengaluru,Bengaluru,Private,360,2012
2,3,MedNova Hospital - Chennai,Chennai,Trust,310,2014
3,4,MedNova Hospital - Pune,Pune,Private,280,2018
4,5,MedNova Hospital - Mumbai,Mumbai,Private,390,2011

In [26]:
patients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12090 entries, 0 to 12089
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   patient_id                 12090 non-null  int64
 1   patient_code               12090 non-null  object
 2   patient_name               12090 non-null  object
 3   age                        11879 non-null  float64
 4   gender                     12090 non-null  object
 5   city                       11920 non-null  object
 6   primary_chronic_condition  8841 non-null   object
 7   insurance_plan             12090 non-null  object
 8   income_segment             12090 non-null  object
 9   registration_date          12090 non-null  object
dtypes: float64(1), int64(1), object(8)
memory usage: 944.7+ KB

In [27]:
admissions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30130 entries, 0 to 30129
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   admission_id        30130 non-null  int64
 1   patient_id          30130 non-null  int64
 2   hospital_id         30130 non-null  int64
 3   department_id       30130 non-null  int64
 4   primary_doctor_id   30130 non-null  int64
 5   admission_date      30130 non-null  object
 6   discharge_date      29879 non-null  object
 7   admission_type      30130 non-null  object
 8   diagnosis           29987 non-null  object
 9   severity_level      30130 non-null  object
 10  discharge_status    30130 non-null  object
 11  readmitted_30_days  30130 non-null  object
dtypes: int64(5), object(7)
memory usage: 2.8+ MB

In [29]:
treatments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90160 entries, 0 to 90159
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   treatment_id      90160 non-null  int64
 1   admission_id      90160 non-null  int64
 2   doctor_id         90160 non-null  int64
 3   treatment_type    90160 non-null  object
 4   treatment_cost    89860 non-null  float64
 5   treatment_date    90160 non-null  object
 6   treatment_status  90160 non-null  object
dtypes: float64(1), int64(3), object(3)
memory usage: 4.8+ MB

In [30]:
billing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30080 entries, 0 to 30079
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   bill_id          30080 non-null  int64
 1   admission_id     30080 non-null  int64
 2   patient_id       30080 non-null  int64
 3   payer_type       30080 non-null  object
 4   gross_amount     29960 non-null  float64
 5   discount_amount  30080 non-null  float64
 6   insurance_paid   30080 non-null  float64
 7   patient_paid     30080 non-null  float64
 8   claim_status     30080 non-null  object
 9   bill_date        30080 non-null  object
dtypes: float64(4), int64(3), object(3)
memory usage: 2.3+ MB

In [31]:
pharmacy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70090 entries, 0 to 70089
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       70090 non-null  int64
 1   admission_id   70090 non-null  int64
 2   patient_id     70090 non-null  int64
 3   medicine_name  70090 non-null  object
 4   quantity       70090 non-null  int64
 5   unit_price     70090 non-null  float64
 6   line_amount    69940 non-null  float64
 7   pharmacy_type  70090 non-null  object
dtypes: float64(2), int64(4), object(2)
memory usage: 4.3+ MB

In [32]:
labs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   lab_id        60000 non-null  int64
 1   admission_id  60000 non-null  int64
 2   patient_id    60000 non-null  int64
 3   test_name     60000 non-null  object
 4   test_value    59880 non-null  float64
 5   test_date     60000 non-null  object
 6   result_flag   60000 non-null  object
dtypes: float64(1), int64(3), object(3)
memory usage: 3.2+ MB

In [33]:
followups.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   followup_id         30000 non-null  int64
 1   admission_id        30000 non-null  int64
 2   patient_id          30000 non-null  int64
 3   followup_due_date   30000 non-null  object
 4   followup_completed  30000 non-null  object
 5   followup_mode       30000 non-null  object
 6   followup_outcome    30000 non-null  object
dtypes: int64(3), object(4)
memory usage: 1.6+ MB

In [34]:
doctors.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   doctor_id         260 non-null    int64
 1   doctor_name       260 non-null    object
 2   department_id     260 non-null    int64
 3   specialization    260 non-null    object
 4   hospital_id       260 non-null    int64
 5   experience_years  260 non-null    int64
 6   doctor_grade      260 non-null    object
dtypes: int64(4), object(3)
memory usage: 14.3+ KB

In [35]:
departments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   department_id    12 non-null     int64
 1   department_name  12 non-null     object
 2   care_complexity  12 non-null     object
dtypes: int64(1), object(2)
memory usage: 420.0+ bytes

In [37]:
hospitals.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   hospital_id     8 non-null      int64
 1   hospital_name   8 non-null      object
 2   city            8 non-null      object
 3   ownership_type  8 non-null      object
 4   bed_capacity    8 non-null      int64
 5   launch_year     8 non-null      int64
dtypes: int64(3), object(3)
memory usage: 516.0+ bytes

# 5. Create a Simple Data Quality Report

This function checks data quality for one table.

Function logic:

- For reach column, find data type
- count missing values
- calculate missing percentage
- count unique values

This is useful because we can applt the same logic to many tables.

In [49]:
def create_quality_report(df, table_name):
    report = pd.DataFrame()
    report['table_name'] = [table_name] * len(df.columns)
    report['column_name'] = df.columns
    report['data_type'] = df.dtypes.astype(str).values
    report['missing_count'] = df.isna().sum().values
    report['missing_percentage'] = (df.isna().mean() * 100).round(2).values
    report['unique_values'] = df.nunique(dropna = True).values
    return report

patients_quality = create_quality_report(patients, 'patients')
admissions_quality = create_quality_report(admissions, 'admissions')
treatments_quality = create_quality_report(treatments, 'treatments')
billing_quality = create_quality_report(billing, 'billing')
pharmacy_quality = create_quality_report(pharmacy, 'pharmacy')
labs_quality = create_quality_report(labs, 'labs')
followups_quality = create_quality_report(followups, 'followups')
doctors_quality = create_quality_report(doctors, 'doctors')
departments_quality = create_quality_report(departments, 'departments')
hospitals_quality = create_quality_report(hospitals, 'hospitals')

quality_report = pd.concat(
    [patients_quality, admissions_quality, treatments_quality, billing_quality, pharmacy_quality, labs_quality, followups_quality, doctors_quality, departments_quality, hospitals_quality],
    ignore_index = True
)

quality_report.head(20)

,table_name,column_name,data_type,missing_count,missing_percentage,unique_values
0,patients,patient_id,int64,0,0.00,12090
1,patients,patient_code,object,0,0.00,12000
2,patients,patient_name,object,0,0.00,12086
3,patients,age,float64,211,1.75,101
4,patients,gender,object,0,0.00,10
5,patients,city,object,170,1.41,14
6,patients,primary_chronic_condition,object,3249,26.87,7
7,patients,insurance_plan,object,0,0.00,5
8,patients,income_segment,object,0,0.00,4
9,patients,registration_date,object,0,0.00,4670
10,admissions,admission_id,int64,0,0.00,30000
11,admissions,patient_id,int64,0,0.00,10966
12,admissions,hospital_id,int64,0,0.00,8
13,admissions,department_id,int64,0,0.00,12
14,admissions,primary_doctor_id,int64,0,0.00,260
15,admissions,admission_date,object,0,0.00,1079
16,admissions,discharge_date,object,251,0.83,1099
17,admissions,admission_type,object,0,0.00,4
18,admissions,diagnosis,object,143,0.47,43
19,admissions,severity_level,object,0,0.00,4

# Clean Patient Master Data

## Business reason
Patient master data is the foundation. If patient age, gender, or chronic condition is wrong, all later analysis becomes weak.

## Cleaning tasks
    1. Remove duplicate patient records
    2. Convert age into number
    3. Handles impossible ages
    4. Standardize gender labels
    5. Standardize chronic condition labels.

In [53]:
patients_clean = patients.copy()
print('Before duplicate removal:', patients_clean.shape)
patients_clean = patients_clean.drop_duplicates()
print('After duplicate removal:', patients_clean.shape)

Before duplicate removal: (12090, 10)
After duplicate removal: (12090, 10)

In [55]:
# convert age to numeric
# If age contains text or invalid values, errors = 'coerce' converts them to NaN
patients_clean['age_clean'] = pd.to_numeric(patients_clean['age'], errors = 'coerce')

# Mark impossible ages as missing
patients_clean.loc[patients_clean['age_clean'] < 0, 'age_clean'] = np.nan
patients_clean.loc[patients_clean['age_clean'] > 110, 'age_clean'] = np.nan

# Fill missing age using median because median is less affected by outliers.
median_age = patients_clean['age_clean'].median()
patients_clean['age_clean'] = patients_clean['age_clean'].fillna(median_age)

patients_clean[['age', 'age_clean']].head(40)

     age  age_clean
0   46.0       46.0
1   58.0       58.0
2   51.0       51.0
3   25.0       25.0
4   54.0       54.0
5    NaN       48.0
6   57.0       57.0
7   66.0       66.0
8   62.0       62.0
9   55.0       55.0
10  46.0       46.0
11  19.0       19.0
12  55.0       55.0
13  51.0       51.0
14  52.0       52.0
15  26.0       26.0
16  29.0       29.0
17  65.0       65.0
18  47.0       47.0
19  59.0       59.0
20  48.0       48.0
21  48.0       48.0
22  63.0       63.0
23  39.0       39.0
24  49.0       49.0
25  40.0       40.0
26  40.0       40.0
27  42.0       42.0
28  51.0       51.0
29  39.0       39.0
30  69.0       69.0
31  32.0       32.0
32  44.0       44.0
33  40.0       40.0
34  72.0       72.0
35  51.0       51.0
36  65.0       65.0
37  22.0       22.0
38  52.0       52.0
39  63.0       63.0

In [56]:
patients_clean['gender'].value_counts()

gender
Female     5957
Male       5577
Other       130
male         71
Unknown      66
M            64
F            64
MALE         57
Femle        56
female       48
Name: count, dtype: int64

In [57]:
# Standardize gender values
patients_clean['gender_clean'] = patients_clean['gender'].astype(str).str.strip().str.lower()

patients_clean['gender_clean'] = patients_clean['gender_clean'].replace({
    'm': 'Male',
    'male': 'Male',
    'f': 'Female',
    'female': 'Female',
    'femle': 'Female',
    'other': 'Other',
    'unknown': 'Unknown',
    'nan': 'Unknown'
})

patients_clean['gender_clean'].value_counts()

gender_clean
Female     6125
Male       5769
Other       130
Unknown      66
Name: count, dtype: int64

In [58]:
patients.head()

,patient_id,patient_code,patient_name,age,gender,city,primary_chronic_condition,insurance_plan,income_segment,registration_date
0,1,P00001,Patient_BKOKF,46.0,Female,Hyderabad,Heart Failure,Premium Insurance,Low,2016-09-25
1,2,P00002,Patient_KXPSW,58.0,Male,Hyderabad,Heart Failure,Basic Insurance,Low,2022-09-12
2,3,P00003,Patient_TJAJT,51.0,Female,Ahmedabad,Hypertension,Government Scheme,Middle,2014-08-02
3,4,P00004,Patient_WYKTO,25.0,Male,None,Heart Failure,Self Pay,Middle,2017-03-23
4,5,P00005,Patient_PFFLA,54.0,Male,None,Asthma,Basic Insurance,Middle,2021-11-22

In [59]:
patients_clean.head()

,patient_id,patient_code,patient_name,age,gender,city,primary_chronic_condition,insurance_plan,income_segment,registration_date,age_clean,gender_clean
0,1,P00001,Patient_BKOKF,46.0,Female,Hyderabad,Heart Failure,Premium Insurance,Low,2016-09-25,46.0,Female
1,2,P00002,Patient_KXPSW,58.0,Male,Hyderabad,Heart Failure,Basic Insurance,Low,2022-09-12,58.0,Male
2,3,P00003,Patient_TJAJT,51.0,Female,Ahmedabad,Hypertension,Government Scheme,Middle,2014-08-02,51.0,Female
3,4,P00004,Patient_WYKTO,25.0,Male,None,Heart Failure,Self Pay,Middle,2017-03-23,25.0,Male
4,5,P00005,Patient_PFFLA,54.0,Male,None,Asthma,Basic Insurance,Middle,2021-11-22,54.0,Male

In [61]:
patients_clean['primary_chronic_condition'].unique()

array(['Heart Failure', 'Hypertension', 'Asthma', 'Diabetes', None,
       'COPD', 'CKD', 'Cancer'], dtype=object)

In [62]:
patients_clean['primary_chronic_condition'].value_counts()

primary_chronic_condition
Hypertension     2387
Diabetes         2134
Asthma           1058
COPD              975
Heart Failure     937
CKD               876
Cancer            474
Name: count, dtype: int64

In [69]:
# Standardize chronic condition values.
patients_clean['chronic_condition_clean'] = patients_clean['primary_chronic_condition'].astype(str).str.strip().str.title()

patients_clean['chronic_condition_clean'].value_counts()

chronic_condition_clean
None             3249
Hypertension     2387
Diabetes         2134
Asthma           1058
Copd              975
Heart Failure     937
Ckd               876
Cancer            474
Name: count, dtype: int64

In [73]:
# Replace missing/blank/unwanted text with unknown
patients_clean['chronic_condition_clean'] = patients_clean['chronic_condition_clean'].replace({
    'Nan': 'Unknown',
    '' : 'Unknown',
    'None': 'Unknown',
    'Null': 'Unknown'
})

patients_clean['chronic_condition_clean'].value_counts()

chronic_condition_clean
Unknown          3249
Hypertension     2387
Diabetes         2134
Asthma           1058
Copd              975
Heart Failure     937
Ckd               876
Cancer            474
Name: count, dtype: int64

In [76]:
# Create chronic flag
# if chronic condition is available, flag = 1
# if missing/unknown, flag = 0

patients_clean['chronic_flag'] = patients_clean['chronic_condition_clean'].apply(
    lambda x: 0 if x == 'Unknown' else 1
)

patients_clean[['primary_chronic_condition', 'chronic_condition_clean', 'chronic_flag']].head(10)

  primary_chronic_condition chronic_condition_clean  chronic_flag
0             Heart Failure           Heart Failure             1
1             Heart Failure           Heart Failure             1
2              Hypertension            Hypertension             1
3             Heart Failure           Heart Failure             1
4                    Asthma                  Asthma             1
5              Hypertension            Hypertension             1
6              Hypertension            Hypertension             1
7                  Diabetes                Diabetes             1
8                      None                 Unknown             0
9                      None                 Unknown             0

In [78]:
patients_clean['chronic_flag'].value_counts()

chronic_flag
1    8841
0    3249
Name: count, dtype: int64

# Clean Admissions Data

## Business reason
Admissions data tells us patient visits, discharge dates, readmissions, department, doctor, and
hospital branch.

## Important derived column
`length_of_stay = discharge_date - admission_date`

This is one of the most important healthcare KPIs.

In [82]:
admissions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30130 entries, 0 to 30129
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   admission_id        30130 non-null  int64
 1   patient_id          30130 non-null  int64
 2   hospital_id         30130 non-null  int64
 3   department_id       30130 non-null  int64
 4   primary_doctor_id   30130 non-null  int64
 5   admission_date      30130 non-null  object
 6   discharge_date      29879 non-null  object
 7   admission_type      30130 non-null  object
 8   diagnosis           29987 non-null  object
 9   severity_level      30130 non-null  object
 10  discharge_status    30130 non-null  object
 11  readmitted_30_days  30130 non-null  object
dtypes: int64(5), object(7)
memory usage: 2.8+ MB

In [81]:
admissions_clean = admissions.copy()
print("Before duplicate removal:", admissions_clean.shape)
admissions_clean = admissions_clean.drop_duplicates()
print("After duplicate removal:", admissions_clean.shape)

Before duplicate removal: (30130, 12)
After duplicate removal: (30000, 12)

In [84]:
# Changing the data types of the data related columns
admissions_clean['admission_date'] = pd.to_datetime(admissions_clean['admission_date'], errors = 'coerce')
admissions_clean['discharge_date'] = pd.to_datetime(admissions_clean['discharge_date'], errors = 'coerce')

In [86]:
admissions_clean['length_of_stay'] = (
    admissions_clean['discharge_date'] - admissions_clean['admission_date']
).dt.days

admissions_clean[['admission_date', 'discharge_date', 'length_of_stay']].head()

  admission_date discharge_date  length_of_stay
0     2024-03-10     2024-03-16             6.0
1     2023-05-19     2023-05-20             1.0
2     2025-06-16     2025-06-18             2.0
3     2025-10-15     2025-10-16             1.0
4     2024-05-07     2024-05-23            16.0

In [88]:
# Handles wrong length of stay values.
# Negative stay means discharge happened before admission, which is impossible.

admissions_clean.loc[admissions_clean['length_of_stay'] < 0, 'length_of_stay'] = np.nan

# Fill missing length of stay using median length of stay
median_loss = admissions_clean['length_of_stay'].median()
admissions_clean['length_of_stay'] = admissions_clean['length_of_stay'].fillna(median_loss)

admissions_clean[['length_of_stay']].head(10)

   length_of_stay
0             6.0
1             1.0
2             2.0
3             1.0
4            16.0
5             2.0
6             2.0
7             4.0
8             4.0
9             5.0

In [89]:
admissions_clean['length_of_stay'].describe()

count    30000.000000
mean         5.915333
std          5.432054
min          1.000000
25%          2.000000
50%          4.000000
75%          8.000000
max         66.000000
Name: length_of_stay, dtype: float64

In [90]:
admissions_clean.head()

,admission_id,patient_id,hospital_id,department_id,primary_doctor_id,admission_date,discharge_date,admission_type,diagnosis,severity_level,discharge_status,readmitted_30_days,length_of_stay
0,1,3415,8,4,123,2024-03-10,2024-03-16,Emergency,Anemia,Critical,Home,Yes,6.0
1,2,3610,8,1,209,2023-05-19,2023-05-20,Planned,Arrhythmia,Moderate,Home,No,1.0
2,3,7584,8,3,190,2025-06-16,2025-06-18,Emergency,Joint Replacement,Moderate,Home,Yes,2.0
3,4,4459,2,3,176,2025-10-15,2025-10-16,Referral,Joint Replacement,Moderate,Home,No,1.0
4,5,5508,3,12,140,2024-05-07,2024-05-23,Planned,Multi Organ Dysfunction,Moderate,Home,No,16.0

In [91]:
admissions_clean['readmitted_30_days'].unique()

array(['Yes', 'No', 'Y', 'FALSE', 'yes', 'TRUE', 'N', 'no'], dtype=object)

In [93]:
admissions_clean['readmitted_clean'].unique()

array(['yes', 'no', 'y', 'false', 'true', 'n'], dtype=object)

In [95]:
# Standardize readmitted 
admissions_clean['readmitted_clean'] = admissions_clean['readmitted_30_days'].astype(str).str.strip().str.lower()

admissions_clean['readmitted_replace'] = admissions_clean['readmitted_clean'].replace({
    'yes': 'Yes',
    'no': 'No',
    'y': 'Yes',
    'false': 'No',
    'true': 'Yes',
    'n': 'No'
})

admissions_clean['readmitted_flag'] = admissions_clean['readmitted_replace'].apply(
    lambda x: 1 if x == 'Yes' else 0
)

admissions_clean.head()

,admission_id,patient_id,hospital_id,department_id,primary_doctor_id,admission_date,discharge_date,admission_type,diagnosis,severity_level,discharge_status,readmitted_30_days,length_of_stay,readmitted_clean,readmitted_replace,readmitted_flag
0,1,3415,8,4,123,2024-03-10,2024-03-16,Emergency,Anemia,Critical,Home,Yes,6.0,yes,Yes,1
1,2,3610,8,1,209,2023-05-19,2023-05-20,Planned,Arrhythmia,Moderate,Home,No,1.0,no,No,0
2,3,7584,8,3,190,2025-06-16,2025-06-18,Emergency,Joint Replacement,Moderate,Home,Yes,2.0,yes,Yes,1
3,4,4459,2,3,176,2025-10-15,2025-10-16,Referral,Joint Replacement,Moderate,Home,No,1.0,no,No,0
4,5,5508,3,12,140,2024-05-07,2024-05-23,Planned,Multi Organ Dysfunction,Moderate,Home,No,16.0,no,No,0

In [98]:
admissions_clean['readmitted_flag'].value_counts(normalize = True) * 100

readmitted_flag
0    51.53
1    48.47
Name: proportion, dtype: float64

# Clean Treatment Cost Data

Treatment cost can contain missing values and extreme outliers.

we will:

    1.Convert cost into numeric.
    2.Identify impossible costs.
    3.Convert impossible costs to missing.
    4.Fill missing cost by treatment type median.

        Why median by treatment type? Because ICU treatment and basic consultation cannot have the samw typical cost.

In [100]:
treatments.head()

,treatment_id,admission_id,doctor_id,treatment_type,treatment_cost,treatment_date,treatment_status
0,1,27337,62,Surgery,52636.30,2023-01-01,Completed
1,2,982,242,Imaging,7478.12,2023-01-01,Completed
2,3,17082,238,Chemotherapy,27451.58,2023-01-01,Completed
3,4,4096,1,Lab Package,3379.43,2023-01-01,Pending
4,5,26108,227,ICU Care,19993.51,2023-01-01,Completed

In [104]:
treatments_clean = treatments.copy()

treatments_clean['treatment_cost'] = pd.to_numeric(treatments_clean['treatment_cost'], errors = 'coerce')

treatments_clean['cost_outlier_flag'] = 0

treatments_clean.head()

,treatment_id,admission_id,doctor_id,treatment_type,treatment_cost,treatment_date,treatment_status,cost_outlier_flag
0,1,27337,62,Surgery,52636.30,2023-01-01,Completed,0
1,2,982,242,Imaging,7478.12,2023-01-01,Completed,0
2,3,17082,238,Chemotherapy,27451.58,2023-01-01,Completed,0
3,4,4096,1,Lab Package,3379.43,2023-01-01,Pending,0
4,5,26108,227,ICU Care,19993.51,2023-01-01,Completed,0

In [105]:
treatments_clean['cost_outlier_flag'].unique()

array([0])

In [113]:
treatments_clean.loc[(treatments_clean['treatment_cost'] < 0) | (treatments_clean['treatment_cost'] > 500000),
'cost_outlier_flag'] = 1

treatments_clean.head()

print("Number of cost outliers:", treatments_clean['cost_outlier_flag'].sum())

Number of cost outliers: 212

In [119]:
# Convert impossible treatment cost into missing value.
treatments_clean.loc[
    treatments_clean['cost_outlier_flag'] == 1, 'treatment_cost'] = np.nan
treatments_clean.head()

,treatment_id,admission_id,doctor_id,treatment_type,treatment_cost,treatment_date,treatment_status,cost_outlier_flag
0,1,27337,62,Surgery,52636.30,2023-01-01,Completed,0
1,2,982,242,Imaging,7478.12,2023-01-01,Completed,0
2,3,17082,238,Chemotherapy,27451.58,2023-01-01,Completed,0
3,4,4096,1,Lab Package,3379.43,2023-01-01,Pending,0
4,5,26108,227,ICU Care,19993.51,2023-01-01,Completed,0

In [1]:
# Fill missing treatment cost using median cost of the same treatment type.
treatments_clean['treatments_cost_clean'] = treatments_clean.groupby('treatment_type')['treatment_cost'].transform(lambda values: values.fillna(values.median()))

treatments_clean[['treatment_type', 'treatment_cost', 'treatments_cost_clean', 'cost_outlier_flag']].head()

NameError: name 'treatments_clean' is not defined

  treatment_type  treatment_cost  treatments_cost_clean  cost_outlier_flag
0        Surgery        52636.30               52636.30                  0
1        Imaging         7478.12                7478.12                  0
2   Chemotherapy        27451.58               27451.58                  0
3    Lab Package         3379.43                3379.43                  0
4       ICU Care        19993.51               19993.51                  0